FROM node:dubnium-alpine

# build
WORKDIR /src
COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . ./
RUN rm -fr dist
RUN ./node_modules/.bin/ember build -e production

FROM nginx:alpine

# configure for SSL
RUN apk add openssl

COPY nginx/extensions.cnf .
COPY nginx/https.conf /etc/nginx/conf.d/

# these steps compatible with MacOS Catalina and newer https://support.apple.com/en-us/HT210176

# self-signed CA cert and key
RUN openssl req -x509 \
    -newkey rsa:2048 -nodes -keyout CA.key \
    -subj "/CN=CA localhost/C=US/ST=CO/O=Ping Identity" \
    -days 825 -sha256 -out CA.crt

# https cert request
RUN openssl req -new \
    -newkey rsa:2048 -nodes -keyout /etc/ssl/private/https.key \
    -subj "/CN=localhost/C=US/ST=CO/O=Ping Identity" \
    -addext "subjectAltName=DNS:localhost" \
    -addext "extendedKeyUsage=serverAuth" \
    -out /etc/ssl/certs/https.csr

# https cert
RUN openssl x509 -req \
    -in /etc/ssl/certs/https.csr \
    -CA CA.crt -CAkey CA.key -CAcreateserial \
    -extfile extensions.cnf \
    -days 825 -sha256 -out /etc/ssl/certs/https.crt

# use nginx runtime envsubst to configure the javascript
COPY nginx/config.js /etc/nginx/templates/config.js.template
ENV NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
ENV NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html/assets

# some defaults
ENV OPEN_BANKING_BASE_URL=https://babbtx-aspsp.herokuapp.com
ENV OPEN_BANKING_API_NAMESPACE=OpenBanking/v2
ENV OAUTH2_AUTHORIZATION_URL=https://auth.pingone.com/7e308ffc-4f09-43be-9574-78c41fe4ac85/as/authorize
ENV OAUTH2_CLIENT_ID=395766d7-bf38-43ff-80f9-74006e38393c
ENV WEBDIS_BASE_URL=""
ENV PERMISSIONS_URL=""

# the compiled SPA
COPY --from=0 /src/dist/ /usr/share/nginx/html/
